[package]
name = "document_vis"
version = "0.1.0"
edition = "2021"
description = "Document Vector Instruction Set (VIS)"

[dependencies]
clap = { workspace = true, features = ["derive"] }
eyre = { workspace = true }
itertools = { workspace = true }
regex = { workspace = true }